### ISSUE TITLE
Inlcuding the original aurhor in License

### ISSUE THREAD

**Issue by antfu** [matheusmazeto/eslint-config#1]
Hey! It seems this repo is based on my https://github.com/antfu/eslint-config, do you mind keeping the original author in the license, as the license is asking? Thanks.

https://github.com/matheusmazeto/eslint-config/blob/807f738874fa76f01310ccc58361ae6db6b466f4/LICENSE#L3

**Comment by matheusmazeto** [comment]
Sure Anthony!
